version: '3.4'
services:
  php:
    volumes:
      - type: bind
        source: .
        target: /var/www
        volume:
          nocopy: true
        consistency: cached # MacOS only
      - /var/www/var

  nginx:
    container_name: kraft-backend_nginx
    build:
      context: .
      target: platform_nginx
    depends_on:
      - php
    volumes:
      - type: bind
        source: ./web
        target: /var/www/web
        volume:
          nocopy: true
        read_only: true
        consistency: cached # MacOS only
    ports:
      - "8088:80"
