version: '3.4'
services:
  php:
    container_name: kraft-backend_php
    build:
      context: .
      target: platform_php
    depends_on:
    - db
    - dbtest
    env_file:
    - .env
    # Comment out these volumes in production
    volumes:
    - type: bind
      source: .
      target: /var/www
      volume:
        nocopy: true
      consistency: cached # MacOS only
    - /var/www/vendor
    - /var/www/var

  nginx:
    container_name: kraft-backend_nginx
    build:
      context: .
      target: platform_nginx
    depends_on:
    - php
    # Comment out this volume in production
    volumes:
    - type: bind
      source: ./web
      target: /var/www/web
      volume:
        nocopy: true
      read_only: true
      consistency: cached # MacOS only
    ports:
    - "8088:80"

  db:
    container_name: kraft-backend_db
    image: mariadb:10.2
    ports:
    - '3308:3306'
    volumes:
    - /var/lib/postgresql/data
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=craft
    restart: unless-stopped

  dbtest:
    container_name: kraft-backend_dbtest
    image: mariadb:10.2
    ports:
    - '3309:3306'
    volumes:
    - /var/lib/postgresql/data
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=craft
    restart: unless-stopped

