version: '3.4'
services:
  db:
    container_name: dismoi-backend-devdb
    image: mariadb:10.2.25
    ports:
      - '3308:3306'
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=lmem
      - MYSQL_PASSWORD=meml
      - MYSQL_DATABASE=kraftbackenddev

  dbtest:
    container_name: dismoi-backend-testdb
    image: mariadb:10.2.25
    ports:
      - '3309:3306'
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=lmem
      - MYSQL_PASSWORD=meml
      - MYSQL_DATABASE=kraftbackenddev

  php:
    container_name: dismoi-backend-php
    build: docker/php
    working_dir: /var/www
    volumes:
    - .:/var/www
    - ./docker/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    - ./docker/php/conf.d/overrides.ini:/usr/local/etc/php/conf.d/overrides.ini
    depends_on:
    - db
    - dbtest

  webserver:
    image: nginx:alpine
    container_name: dismoi-backend-webserver
    working_dir: /var/www
    volumes:
      - ./var/logs:/var/www/logs
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8088:80"
    depends_on:
      - php