<?php

namespace AppBundle\Repository;

/**
 * AlternativeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlternativeRepository extends \Doctrine\ORM\EntityRepository
{
}
