<?php

namespace AppBundle\Repository;

/**
 * ContributorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContributorRepository extends \Doctrine\ORM\EntityRepository
{
}
