<?php

namespace AppBundle\Repository;

/**
 * FilterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilterRepository extends \Doctrine\ORM\EntityRepository
{
}
