<?php

namespace AppBundle\Repository;
use AppBundle\Entity\RecommendationVisibility;

/**
 * MatchingContextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchingContextRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllPrivate(){
        return $this->getEntityManager()
                    ->createQuery('SELECT mc FROM AppBundle:MatchingContext mc JOIN mc.recommendation r WHERE r.visibility = ?1')
                    ->setParameter(1, RecommendationVisibility::PRIVATE_VISIBILITY()->getValue())
                    ->getResult();
    }
}
